### ISSUE TITLE
Issue while building locally

### ISSUE THREAD

**Issue by btalanski** [b3ck/sls-b3ck-edit#1]
I decided to instead of pulling the image from docker hub to try and build it locally first.

While building I noticed the build was failing every time on this step:

```
COPY --from=build /usr/local/lib64/libsrt* /usr/local/lib64/
```
I've updated this step to the following:
```
COPY --from=build /usr/local/lib/libsrt* /usr/local/lib/
```
And with that I was able to successfully build the image and start the container. I'm not sure if this is really an issue as I'm no expert on docker or building libs with `make`, but anyways, that's what worked for me.

**Comment by DigibitDK** [comment]
Confirmed - Same on mattwb65.
Fix worked for me as well.

**Comment by b3ck** [comment]
updated.
