### ISSUE TITLE
Questions ... 

### ISSUE THREAD

**Issue by DigibitDK** [b3ck/sls-b3ck-edit#2]
Hi B3ck.

What's the reason for using /var/run/docker.sock:/var/run/docker.sock in the docker? (Its not even in Read-Only mode?)
Does SLS need to have access to the host-system for any reason?

Best Regards
Michael

**Comment by b3ck** [comment]
Where do you see `/var/run/docker.sock:/var/run/docker.sock` ?

**Comment by DigibitDK** [comment]
https://hub.docker.com/r/b3ckontwitch/sls-b3ck-edit

docker run -d -p 30000:30000/udp -p 8181:8181/tcp --name=sls-b3ck-edit --restart=always --pull=always -v /var/run/docker.sock:/var/run/docker.sock -v sls-b3ck-edit_data:/data b3ckontwitch/sls-b3ck-edit

**Comment by b3ck** [comment]
> https://hub.docker.com/r/b3ckontwitch/sls-b3ck-edit
> 
> docker run -d -p 30000:30000/udp -p 8181:8181/tcp --name=sls-b3ck-edit --restart=always --pull=always -v /var/run/docker.sock:/var/run/docker.sock -v sls-b3ck-edit_data:/data b3ckontwitch/sls-b3ck-edit

That's just a command alternative, you can change it to do whatever you want, during my testing this command worked best for me, if it doesn't for you feel free to change it.

-b3ck

Also, in regards to your deleted question:

> And what's the changes in this version compared to mattwb65s? Why are your version more IRL-friendly? Guess that mattwb65s version has the same functions (?)

The only thing I did was add some things in the beginning of the server boot up, links etc.. and added it to dockerhub.. I just wanted to make it easier to deploy.

**Comment by DigibitDK** [comment]
Copy that - Thanks :)
