### ISSUE TITLE
SRT Source 1.4.4

### ISSUE THREAD

**Issue by timtam85465414** [b3ck/sls-b3ck-edit#3]
Hi! Will this be updated to support SRT Source 1.4.4 ? (https://github.com/Haivision/srt/releases)

Thank you !

**Comment by b3ck** [comment]
Yes this will always pull the latest master of SRT when using the dockerfile:
![image](https://user-images.githubusercontent.com/1740542/146688583-b21e281d-9c3f-4fc4-942e-a60f3ca0fe13.png)
