### ISSUE TITLE
error while building locally

### ISSUE THREAD

**Issue by tokon2000** [b3ck/sls-b3ck-edit#4]
If I want to build the container locally I get the following error:

> srt-live-server.cpp: In function 'int main(int, char**)':
srt-live-server.cpp:205:29: error: invalid operands of types 'int' and 'std::nullptr_t' to binary 'operator!='
  205 |     if (conf_srt->http_port != NULL) {
      |                             ^
make: *** [Makefile:54: all] Error 1
The command '/bin/sh -c make -j8' returned a non-zero code: 2

With mattwb65's version it is the same.
What's going wrong?

**Comment by tokon2000** [comment]
Found a solution:

`if (conf_srt->http_port != 0) {`
or
`if (long(conf_srt->http_port) != long(NULL)) {`

Both is working, but I don't know which one is the right/better code.

**Comment by DigibitDK** [comment]
I have the same issue.

**Comment by b3ck** [comment]
`if (conf_srt->http_port != 0) {` is better
