### ISSUE TITLE
Max latency "2899"

### ISSUE THREAD

**Issue by timtam85465414** [b3ck/sls-b3ck-edit#5]
When pushing a SRT stream (with larix broadcaster) with more than "2899ms" latency (for exemple set to 3000ms or more) it won't work for some reasons. Tried everything, edited sls.conf etc :(

**Comment by timtam85465414** [comment]
@b3ck maybe that's the problem, looks like 3 files has been updated after your cloned version ?
https://gitlab.com/mattwb65/srt-live-server/-/commit/b2f1bbe8bb4a6241c5ab032b5082e706e28d091e

(tried with the updated files and i could set up more than 2899ms latency)

**Comment by timtam85465414** [comment]
@b3ck maybe that's the problem, looks like 3 files has been updated after your cloned version ?
https://gitlab.com/mattwb65/srt-live-server/-/commit/b2f1bbe8bb4a6241c5ab032b5082e706e28d091e

ps: i'm using docker

**Comment by b3ck** [comment]
It was an edit from Matt's original release, to support SRTLA streams but not the actual SRTLA protocol.

**Comment by timtam85465414** [comment]
Found why, in sls.conf, "idle_streams_timeout" needs a greater value than the "latency" setting.
Example : latency is set to 3500ms, idle_stream_timeout set to 5.
